FROM nginx:latest # you can use any type of image like alpine, stable, etc  
# Set the maintainer information
LABEL maintainer="Abrar Akbar <abrarakbar623@gmial.com>"
COPY ./default.conf /etc/nginx/conf.d/default.conf 
